
[2021-05-01 14:50:40] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 187, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
TypeError: embed_browser() takes 3 positional arguments but 5 were given


[2021-05-01 14:51:48] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 293, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 14:52:22] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 187, in on_button_pressed
    self.embed_browser(start,end)
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 243, in embed_browser
    gmap.scatter(lat,lng,color=['blue', 'orange'])
NameError: name 'lat' is not defined


[2021-05-01 14:54:00] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 187, in on_button_pressed
    self.embed_browser(start,end)
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 244, in embed_browser
    gmap.plot(*path,edge_width=7,color='red')
UnboundLocalError: local variable 'path' referenced before assignment


[2021-05-01 14:55:23] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 187, in on_button_pressed
    self.embed_browser(start,end)
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 245, in embed_browser
    gmap.plot(*path,edge_width=7,color='red')
NameError: name 'path' is not defined


[2021-05-01 14:55:38] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 187, in on_button_pressed
    self.embed_browser(start,end)
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 246, in embed_browser
    gmap.draw("map.html")
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1050, in draw
    self._write_html(w)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1121, in _write_html
    self.write_points(w, color_cache)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1187, in write_points
    self.write_point(w, point[0], point[1], point[2], point[3], point[4], color_cache, point[5], point[6], point[7]) # TODO: Not maintainable.
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1235, in write_point
    marker = _Marker(_format_LatLng(lat, lng, precision), name=marker_name, title=title, label=label, icon=marker_icon.name, draggable=draggable)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 52, in _format_LatLng
    return 'new google.maps.LatLng(%.*f, %.*f)' % (precision, lat, precision, lng)
TypeError: must be real number, not str


[2021-05-01 14:56:30] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 187, in on_button_pressed
    self.embed_browser(start,end)
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 246, in embed_browser
    gmap.draw("map.html")
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1050, in draw
    self._write_html(w)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1121, in _write_html
    self.write_points(w, color_cache)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1187, in write_points
    self.write_point(w, point[0], point[1], point[2], point[3], point[4], color_cache, point[5], point[6], point[7]) # TODO: Not maintainable.
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1235, in write_point
    marker = _Marker(_format_LatLng(lat, lng, precision), name=marker_name, title=title, label=label, icon=marker_icon.name, draggable=draggable)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 52, in _format_LatLng
    return 'new google.maps.LatLng(%.*f, %.*f)' % (precision, lat, precision, lng)
TypeError: must be real number, not str


[2021-05-01 14:58:13] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 187, in on_button_pressed
    self.embed_browser(start,end)
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 246, in embed_browser
    gmap.draw("map.html")
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1050, in draw
    self._write_html(w)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1121, in _write_html
    self.write_points(w, color_cache)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1187, in write_points
    self.write_point(w, point[0], point[1], point[2], point[3], point[4], color_cache, point[5], point[6], point[7]) # TODO: Not maintainable.
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1235, in write_point
    marker = _Marker(_format_LatLng(lat, lng, precision), name=marker_name, title=title, label=label, icon=marker_icon.name, draggable=draggable)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 52, in _format_LatLng
    return 'new google.maps.LatLng(%.*f, %.*f)' % (precision, lat, precision, lng)
TypeError: must be real number, not str


[2021-05-01 14:59:08] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 187, in on_button_pressed
    self.embed_browser(start,end)
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 246, in embed_browser
    gmap.draw("map.html")
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1050, in draw
    self._write_html(w)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1121, in _write_html
    self.write_points(w, color_cache)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1187, in write_points
    self.write_point(w, point[0], point[1], point[2], point[3], point[4], color_cache, point[5], point[6], point[7]) # TODO: Not maintainable.
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1235, in write_point
    marker = _Marker(_format_LatLng(lat, lng, precision), name=marker_name, title=title, label=label, icon=marker_icon.name, draggable=draggable)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 52, in _format_LatLng
    return 'new google.maps.LatLng(%.*f, %.*f)' % (precision, lat, precision, lng)
TypeError: must be real number, not str


[2021-05-01 15:01:27] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 187, in on_button_pressed
    self.embed_browser(start,end)
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 246, in embed_browser
    gmap.draw("map.html")
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1050, in draw
    self._write_html(w)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1121, in _write_html
    self.write_points(w, color_cache)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1187, in write_points
    self.write_point(w, point[0], point[1], point[2], point[3], point[4], color_cache, point[5], point[6], point[7]) # TODO: Not maintainable.
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1235, in write_point
    marker = _Marker(_format_LatLng(lat, lng, precision), name=marker_name, title=title, label=label, icon=marker_icon.name, draggable=draggable)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 52, in _format_LatLng
    return 'new google.maps.LatLng(%.*f, %.*f)' % (precision, lat, precision, lng)
TypeError: must be real number, not str


[2021-05-01 15:11:05] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 187, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 245, in embed_browser
    gmap.plot(*path,edge_width=7,color='red')
UnboundLocalError: local variable 'path' referenced before assignment


[2021-05-01 15:23:27] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 306, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 15:40:22] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 313, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 15:43:40] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 320, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 15:53:41] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 192, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 233, in embed_browser
    if self.wheelChair is False:
AttributeError: 'MainFrame' object has no attribute 'wheelChair'


[2021-05-01 15:54:50] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 316, in OnSize
    self.browser.NotifyMoveOrResizeStarted()
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 16:19:31] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 363, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'

